//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_Documental.Modelo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class centroeducativo
    {
        public centroeducativo()
        {
            this.documentos = new HashSet<documentos>();
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int id_centroEducativo { get; set; }
        public string nombre_director { get; set; }
        public string direccion { get; set; }
        public string CIF { get; set; }
        public string telefono { get; set; }
        public Nullable<int> fax { get; set; }
        public Nullable<int> cp { get; set; }
        public string nombreCentro { get; set; }
    
        public virtual ICollection<documentos> documentos { get; set; }
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
