//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_Documental.Modelo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class centrotrabajo
    {
        public int id_centroTrabajo { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string nombreCentro { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
