//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_Documental.Modelo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public permisos()
        {
            this.rol = new HashSet<rol>();
        }
    
        public int id_permiso { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<rol> rol { get; set; }
    }
}
