//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_Documental.Modelo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol
    {
        public rol()
        {
            this.usuarios = new HashSet<usuarios>();
            this.permisos = new HashSet<permisos>();
        }
    
        public int id_rol { get; set; }
        public string tipoRol { get; set; }
    
        public virtual ICollection<usuarios> usuarios { get; set; }
        public virtual ICollection<permisos> permisos { get; set; }
    }
}
