//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_Documental.Modelo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id_usuario { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<int> id_centroEducativo { get; set; }
        public string observaciones { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
    
        public virtual centroeducativo centroeducativo { get; set; }
        public virtual rol rol { get; set; }
    }
}
